Repository jalaluddin/smartshop, pull requests merged in 2018-03, with the labels that each got.

#17 Feature/ss shovon ajax
  SmartShop.Data/SmartShop.Data.csproj
  SmartShop.Data/SortElement.cs
  SmartShop.Inventory/ProductCategoryManagementService.cs
  SmartShop.Web/Areas/Admin/Controllers/ProductCategoryController.cs
  SmartShop.Web/Areas/Admin/Views/ProductCategory/Add.cshtml
  SmartShop.Web/Areas/Admin/Views/ProductCategory/List.cshtml
  SmartShop.Web/Areas/Admin/Views/ProductCategory/List2.cshtml
  SmartShop.Web/Areas/Admin/Views/Shared/_Header.cshtml
  SmartShop.Web/Areas/Admin/Views/Shared/_SideMenu.cshtml
  SmartShop.Web/Controllers/CheckoutController.cs
  SmartShop.Web/Logs/Errors.log.2018-02-20
  SmartShop.Web/Models/DataTablesAjaxRequestModel.cs
  SmartShop.Web/Models/Sample.cs
  SmartShop.Web/SmartShop.Web.csproj
  SmartShop.Web/packages.config
Labels: help wanted

#26 Refine product category Add
  SmartShop.Inventory/ProductCategoryManagementService.cs
  SmartShop.Web/Areas/Admin/Controllers/ProductCategoryController.cs
  SmartShop.Web/Areas/Admin/Models/ProductCategoryModel.cs
  SmartShop.Web/Areas/Admin/Views/ProductCategory/Add.cshtml
Labels: feature

#30 Feature/ss 27
  SmartShop.Inventory/Product.cs
  SmartShop.Inventory/ProductAdditionalInformation.cs
  SmartShop.Inventory/ProductImage.cs
  SmartShop.Inventory/ProductReviews.cs
  SmartShop.Inventory/ProductType.cs
  SmartShop.Inventory/SmartShop.Inventory.csproj
  SmartShop.Web/Areas/Admin/Models/ProductListModel.cs
  SmartShop.Web/Areas/Admin/Views/Product/List.cshtml
Labels: feature

#33 Product Basic Add complete.
  SmartShop.Inventory/ProductManagementService.cs
  SmartShop.Web/Areas/Admin/Controllers/ProductController.cs
  SmartShop.Web/Areas/Admin/Models/PorductModel.cs
  SmartShop.Web/Areas/Admin/Models/ProductModel.cs
  SmartShop.Web/Areas/Admin/Views/Product/Add.cshtml
  SmartShop.Web/Areas/Admin/Views/Product/List.cshtml
  SmartShop.Web/SmartShop.Web.csproj
Labels: feature

#47 Feature/ss 43
  SmartShop.Inventory/ProductAdditionalInformation.cs
  SmartShop.Inventory/ProductImage.cs
  SmartShop.Inventory/ProductManagementContext.cs
  SmartShop.Inventory/ProductManagementService.cs
  SmartShop.Web/Areas/Admin/Controllers/ProductController.cs
  SmartShop.Web/Areas/Admin/Views/Product/Add.cshtml
  SmartShop.Web/Areas/Admin/Views/Product/List.cshtml
  SmartShop.Web/Content/flexslider.css
  SmartShop.Web/Controllers/HomeController.cs
  SmartShop.Web/Models/ProductModel.cs
  SmartShop.Web/SmartShop.Web.csproj
  SmartShop.Web/Views/Home/Details.cshtml
  SmartShop.Web/Views/Shared/_NavigationPartial.cshtml
Labels: enhancement
